name: Build Packages

on:
    push:
        branches: ['master', 'BRANCH*']
        paths: ['ganttproject-builder/VERSION']

jobs:
    distZip:
        runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Checkout submodules
          shell: bash
          run: |
              git submodule sync --recursive
              git submodule update --init --force --recursive --depth=1
        - uses: actions/setup-java@v3
          with:
              distribution: 'liberica'
              java-version: 17.0.5
              java-package: jdk+fx
              cache: 'gradle'
        - name: Build GanttProject
          run: ./gradlew distzip

        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
              credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

        - name: 'Set up Cloud SDK'
          uses: 'google-github-actions/setup-gcloud@v1'

        - name: 'Use gcloud CLI'
          run: 'gcloud info'

        - name: Upload ZIP
          run: |
              gsutil cp ganttproject-builder/build/distributions/*.zip gs://dl.ganttproject.biz

#  packageLinux:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Checkout submodules
#        shell: bash
#        run: |
#          git submodule sync --recursive
#          git submodule update --init --force --recursive --depth=1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 17.0.4
#          java-package: jdk+fx
#
#      - name: Build self-contained package for Linux
#        run: |
#          gradle distbin
#          gradle distbin
#          build-bin/package-lin.sh build ganttproject-builder/dist-bin 2.99.0 ''
#
#      - name: Build ZIP archive
#        run: |
#          gradle distzip
#
#      - name: Upload to Dropbox
#        env:
#          ACCESS_TOKEN: ${{ secrets.GANTTPROJECT_BUILDS_ACCESS_TOKEN }}
#        run: |
#          cd build/dist
#          ls -l
#          for f in *; do curl -X POST https://content.dropboxapi.com/2/files/upload \
#              --header "Authorization: Bearer ${ACCESS_TOKEN}" \
#              --header "Dropbox-API-Arg: {\"path\": \"/$f\", \"mode\" : \"overwrite\"}" \
#              --header "Content-Type: application/octet-stream" \
#              --data-binary "@$f"; done
#
#  packageMacOs:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Checkout submodules
#        shell: bash
#        run: |
#          git submodule sync --recursive
#          git submodule update --init --force --recursive --depth=1
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 11.0.5
#          java-package: jdk+fx
#
#      - name: Build self-contained package for macOS
#        run: |
#          gradle distbin
#          gradle distbin
#          build-bin/package-mac.sh build ganttproject-builder/dist-bin 2.99.0 ''
#
#      - name: Upload to Dropbox
#        env:
#          ACCESS_TOKEN: ${{ secrets.GANTTPROJECT_BUILDS_ACCESS_TOKEN }}
#        run: |
#          cd build/dist
#          for f in *; do curl -X POST https://content.dropboxapi.com/2/files/upload \
#              --header "Authorization: Bearer ${ACCESS_TOKEN}" \
#              --header "Dropbox-API-Arg: {\"path\": \"/$f\", \"mode\" : \"overwrite\"}" \
#              --header "Content-Type: application/octet-stream" \
#              --data-binary "@$f"; done
